name: Deploy to repo.obydux.win

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish to snapshot repository
        env:
          OBYDUX_REPO_USERNAME: ${{ secrets.OBYDUX_REPO_USERNAME }}
          OBYDUX_REPO_PASSWORD: ${{ secrets.OBYDUX_REPO_PASSWORD }}
        run: ./gradlew publish